spring:
  cloud:
    gateway:
      routes:
        - id: posts-routes
          uri: ${POSTS_ROUTE_URI:http://localhost:8000}
          predicates:
            - Path=/posts/**
          filters:
            - PrefixPath=/api
            - AddResponseHeader=X-Powered-By, TestGateway Service
